"""add_buffett_columns

Revision ID: 2fec99cf2906
Revises: f39214999d97
Create Date: 2026-04-24 16:43:44.631258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fec99cf2906'
down_revision = 'f39214999d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_earnings', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('intrinsic_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('quality_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('growth_rate_used', sa.Float(), nullable=True))

    with op.batch_alter_table('user_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_rate', sa.Float(), nullable=False,
                                      server_default='0.09'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_configs', schema=None) as batch_op:
        batch_op.drop_column('discount_rate')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('growth_rate_used')
        batch_op.drop_column('quality_score')
        batch_op.drop_column('intrinsic_value')
        batch_op.drop_column('owner_earnings')

    # ### end Alembic commands ###
